version: '3.4'

services:
  pluralsightmoviestore.client:
    image: azurekubertntesedemo.azurecr.io/pluralsightmoviestoreclient 
    build:
      context: .
      dockerfile: PluralsightMovieStore.Client/Dockerfile
    depends_on: 
        - "pluralsightpricing.api"
  pluralsightpricing.api:
    image: azurekubertntesedemo.azurecr.io/pluralsightpricingapi
    build:
      context: .
      dockerfile: PluralsightPricing.API/Dockerfile

