version: '3.4'

services:
  pluralsightmoviestore.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  pluralsightpricing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

